name: hdsrhipy
channels:
  - conda-forge
  - default
dependencies:
  - python
  - git
  - pip
  - flopy
  - pastas
  - scikit-learn
  - ipykernel
  - pymannkendall
  - contextily
  - ipywidgets
  - geopandas
  - rasterio
  - jupyterlab
  - imod
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pillow
  - rasterstats
  - tqdm
  - rioxarray
  - openpyxl
  - descartes

  